server:
  host: "localhost"
  port: 8080

database:
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  name: "mydatabase"

logging:
  level: "INFO"
  file: "/var/log/myapp.log"

features:
  enable_feature_x: true
  enable_feature_y: false

users:
  - username: "admin"
    password: "adminpassword"
    roles:
      - "admin"
      - "user"
  - username: "guest"
    password: "guestpassword"
    roles:
      - "user"
